// Fill the DB with example data on startup

import { Meteor } from 'meteor/meteor';
import { Links } from '../../api/links/links.js';
import { Pests } from '../../api/pests/pests.js';
import { CMS } from '../../api/cms/cms.js';

Meteor.startup(() => {
  // if the Links collection is empty
  if (Links.find().count() === 0) {
    const data = [
      {
        title: 'Do the Tutorial',
        url: 'https://www.meteor.com/try',
        createdAt: new Date(),
      },
      {
        title: 'Follow the Guide',
        url: 'http://guide.meteor.com',
        createdAt: new Date(),
      },
      {
        title: 'Read the Docs',
        url: 'https://docs.meteor.com',
        createdAt: new Date(),
      },
      {
        title: 'Discussions',
        url: 'https://forums.meteor.com',
        createdAt: new Date(),
      },
    ];

    data.forEach(link => Links.insert(link));
  }

  // if the CMS collection is empty
  if (CMS.find().count() === 0) {
    const data = [
        {
          info: 'finalLib',
          bannerContentPosition: 'middle',
          bannerImage: '/img/banners/pest_lib_banner.jpg',
          bannerImageID: '',
          bannerHeadText: 'Pest Library',
          bannerSubText: 'An online library for Rice and Corn Pests',
          searchLabelText: 'Search the library for pests',
          viewPestType: ['Rice', 'Corn'],
          pestsPerPage: 8
        }
    ];

    data.forEach(cms => CMS.insert(cms));
  }

  // if the Pests collection is empty
  if (Pests.find().count() === 0) {
    const data = [
        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: 'Sira ang mga dulo ng dahon pati ang mga gilid nito. Kaya nitong kainin ang buong dahon. Kaya rin nitong maputol ang uhay mula sa puno nito.',
          fil_part_destroyed: 'Puno, dahon, murang palay, uhay',
          fil_stage_threatening: 'Larva',
          fil_symptoms: 'Nawawala ang mga dahon. Tumba at putol na puno ng palay. Ang mga pausbong pa lang na mga uhay ay nawawala. Mas mapapansin sila kung gabi o kaya ay kapag makulimlim dahil mas aktibo sila sa mga oras na ito.',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: 'Kultural na pamamaraan: Bunutin ang mga damo dahil nagsisilbi itong alternatibong tirahan ng Armyworm. Patayin ang mga uod sa pamamagitan ng pagtataas ng lebel ng tubig. Ang seedbed ay dapat malayo sa damuhan.; Natural na pamamaraan: Iwasang patayin ang mga natural na kalaban nito gaya ng Tachinid Fly.',
          fil_name: 'Harabas',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Gross feeding damage to foliage, growing points, and young stems. Severe infestation results in total defoliation or destruction of the plant to ground level.',
          description: 'Eggs: Pale-yellowish and becomes dark brown just before hatching. The black head-capsules of the larvae can be seen through the shells. Each egg is about 0.5 mm in diameter, conical with a slightly rounded apex and a densely sculpted surface; Larvae: Develops from grey-green with white-yellow stripes down its back when small, to black with thin blue lines down the middle of the back and yellow-green lines outside the blue lines when fully grown. It measures 2 to 3cm long, has a velvety-black upper surface with pale lateral lines, a green or yellow ventral surface, and no hairs on the body. There are three parallel lines on the dorsal surface of the prothoracic (first body) segment and a stripe running longitudinally down the mid-dorsal surface of the body is always paler than the black pigmentation on either side of it. The head is always shiny-black; Pupa: Mahogany-brown, 10-14mm long, with a smooth, shiny surface; Adult: It is 14-18mm long and has a 29-32mm wing span. The abdomen is covered with pale grey-brown scales (except for the tip in the female which has black hair-scales). Forewings are dark-brown with distinctive grey-black markings. Hindwings are white with dark veins.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Noctuidae',
          classification: '',
          treatment: 'Many animals, birds and insects prey on the African armyworm at different stages of its life cycle. These natural enemies should be encouraged by maintaining natural surroundings with plenty of breeding places for them, including trees and shrubs. Night birds and bats feed on the African armyworm moths, and lacewings, wasps, parasitic wasps and spiders eat the caterpillars; Avoid burning and overgrazing of grasslands which are the natural habitat and food store of the caterpillars. Burning often causes outbreaks because as soon as temperatures rise, eggs are laid in large quantities on the fresh new grass.',
          sci_name: 'Spodoptera exempta (Walker)/Mythimna separata Walker/Spodoptera mauritia Boisduval',
          eng_name: 'African Armyworm, Black Armyworm, Nutgrass Armyworm, True Armyworm, Hail Worm, Mystery Armyworm, Rain Worm',
          name: 'Black Armyworm adult',
          image: '/img/pests/BlackArmywormadult.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: 'Sira ang mga dulo ng dahon pati ang mga gilid nito. Kaya nitong kainin ang buong dahon. Kaya rin nitong maputol ang uhay mula sa puno nito.',
          fil_part_destroyed: 'Puno, dahon, murang palay, uhay',
          fil_stage_threatening: 'Larva',
          fil_symptoms: 'Nawawala ang mga dahon. Tumba at putol na puno ng palay. Ang mga pausbong pa lang na mga uhay ay nawawala. Mas mapapansin sila kung gabi o kaya ay kapag makulimlim dahil mas aktibo sila sa mga oras na ito.',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: 'Kultural na pamamaraan: Bunutin ang mga damo dahil nagsisilbi itong alternatibong tirahan ng Armyworm. Patayin ang mga uod sa pamamagitan ng pagtataas ng lebel ng tubig. Ang seedbed ay dapat malayo sa damuhan.; Natural na pamamaraan: Iwasang patayin ang mga natural na kalaban nito gaya ng Tachinid Fly.',
          fil_name: 'Harabas',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Gross feeding damage to foliage, growing points, and young stems. Severe infestation results in total defoliation or destruction of the plant to ground level.',
          description: 'Eggs: Pale-yellowish and becomes dark brown just before hatching. The black head-capsules of the larvae can be seen through the shells. Each egg is about 0.5 mm in diameter, conical with a slightly rounded apex and a densely sculpted surface; Larvae: Develops from grey-green with white-yellow stripes down its back when small, to black with thin blue lines down the middle of the back and yellow-green lines outside the blue lines when fully grown. It measures 2 to 3cm long, has a velvety-black upper surface with pale lateral lines, a green or yellow ventral surface, and no hairs on the body. There are three parallel lines on the dorsal surface of the prothoracic (first body) segment and a stripe running longitudinally down the mid-dorsal surface of the body is always paler than the black pigmentation on either side of it. The head is always shiny-black; Pupa: Mahogany-brown, 10-14mm long, with a smooth, shiny surface; Adult: It is 14-18mm long and has a 29-32mm wing span. The abdomen is covered with pale grey-brown scales (except for the tip in the female which has black hair-scales). Forewings are dark-brown with distinctive grey-black markings. Hindwings are white with dark veins.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Noctuidae',
          classification: '',
          treatment: 'Many animals, birds and insects prey on the African armyworm at different stages of its life cycle. These natural enemies should be encouraged by maintaining natural surroundings with plenty of breeding places for them, including trees and shrubs. Night birds and bats feed on the African armyworm moths, and lacewings, wasps, parasitic wasps and spiders eat the caterpillars; Avoid burning and overgrazing of grasslands which are the natural habitat and food store of the caterpillars. Burning often causes outbreaks because as soon as temperatures rise, eggs are laid in large quantities on the fresh new grass.',
          sci_name: 'Spodoptera exempta (Walker)/Mythimna separata Walker/Spodoptera mauritia Boisduval',
          eng_name: 'African Armyworm, Black Armyworm, Nutgrass Armyworm, True Armyworm, Hail Worm, Mystery Armyworm, Rain Worm',
          name: 'Black Armyworm larva',
          image: '/img/pests/BlackArmywormlarva.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: '',
          description: 'Egg: Laid in clusters covered with short yellowish brown hairs from the abdominal tips of the female moths. Each egg is pearly white, round, and has a ridged surface; Larva: Brown or green with longitudinal stripes, with black spots ringing the body about one-fourth of the body length behind the head; Adult: Has 15-20mm long grey-brown body, and a wingspan of 30-38mm. The forewings are grey to reddish-brown with a strongly variegated pattern and paler lines along the veins, and the hindwings are greyish-white with grey margins.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Noctuidae',
          classification: '',
          treatment: 'Seedbeds should be established far from large areas of weeds, remove weeds from areas outside of fields, and plow all uncultivated land. In insecticides, sprays are more effective than granules. High dosages are required to kill large armyworm and cutworm larvae. Spraying should be done late in the afternoon before the larvae leave their resting places to climb up the plants. Because damage is normally concentrated in discrete areas of a rice field, only areas where damage occurs should be sprayed.',
          sci_name: 'Spodoptera litura (Fabricius)',
          eng_name: 'Common Cutworm, Grass Cutworm, Vegetable Cutworm, Tobacco Cutworm, Tobacco Caterpillar, Taro Caterpillar',
          name: 'Common Cutworm adult',
          image: '/img/pests/CommonCutwormadult.jpg'
       },
        
        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: '',
          description: 'Egg: Laid in clusters covered with short yellowish brown hairs from the abdominal tips of the female moths. Each egg is pearly white, round, and has a ridged surface; Larva: Brown or green with longitudinal stripes, with black spots ringing the body about one-fourth of the body length behind the head; Adult: Has 15-20mm long grey-brown body, and a wingspan of 30-38mm. The forewings are grey to reddish-brown with a strongly variegated pattern and paler lines along the veins, and the hindwings are greyish-white with grey margins.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Noctuidae',
          classification: '',
          treatment: 'Seedbeds should be established far from large areas of weeds, remove weeds from areas outside of fields, and plow all uncultivated land. In insecticides, sprays are more effective than granules. High dosages are required to kill large armyworm and cutworm larvae. Spraying should be done late in the afternoon before the larvae leave their resting places to climb up the plants. Because damage is normally concentrated in discrete areas of a rice field, only areas where damage occurs should be sprayed.',
          sci_name: 'Spodoptera litura (Fabricius)',
          eng_name: 'Common Cutworm, Grass Cutworm, Vegetable Cutworm, Tobacco Cutworm, Tobacco Caterpillar, Taro Caterpillar',
          name: 'Common Cutworm larva',
          image: '/img/pests/CommonCutwormlarva.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: '',
          description: 'Egg: Laid in rows along leaves, which fold over and protect the eggs. The pale yellow, spherical eggs can be seen when the leaf blade is unfolded; Larva: Usually light brown or gray green, with a longitudinal dark band midway down the side of the body; Pupa: Shiny, yellowish-brown; Adult: Wing span is 38-48 mm. Forewings are grayish-yellow, with dark-gray or reddish-yellow tint. External wing margin blackened obliquely from top backward, with dark stroke and with a row of dark points. Hindwings are gray, with dark external margin. Antennae are thread-like.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Noctuidae',
          classification: '',
          treatment: 'Weeding, inter-row cultivations, removal of crop residues from fields after harvesting, deep autumn plowing, optimal dates of early sowing, cultivation of resistant varieties, insecticide treatments of crops, release of such entomophages as Trichogramma spp.',
          sci_name: 'Mythimna separata (Walker)',
          eng_name: 'Ear-cutting caterpillar, Oriental Armyworm, Northern Armyworm',
          name: 'Ear-cutting Caterpillar adult',
          image: '/img/pests/Ear-cuttingCaterpillaradult.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: '',
          description: 'Egg: Laid in rows along leaves, which fold over and protect the eggs. The pale yellow, spherical eggs can be seen when the leaf blade is unfolded; Larva: Usually light brown or gray green, with a longitudinal dark band midway down the side of the body; Pupa: Shiny, yellowish-brown; Adult: Wing span is 38-48 mm. Forewings are grayish-yellow, with dark-gray or reddish-yellow tint. External wing margin blackened obliquely from top backward, with dark stroke and with a row of dark points. Hindwings are gray, with dark external margin. Antennae are thread-like.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Noctuidae',
          classification: '',
          treatment: 'Weeding, inter-row cultivations, removal of crop residues from fields after harvesting, deep autumn plowing, optimal dates of early sowing, cultivation of resistant varieties, insecticide treatments of crops, release of such entomophages as Trichogramma spp.',
          sci_name: 'Mythimna separata (Walker)',
          eng_name: 'Ear-cutting caterpillar, Oriental Armyworm, Northern Armyworm',
          name: 'Ear-cutting Caterpillar larva',
          image: '/img/pests/Ear-cuttingCaterpillarlarva.jpg'
       },
        
        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: '',
          description: 'Egg: Laid in small clusters openly on the leaf blades. Each egg is spherical and shiny; Larva: Has two pairs of white or black horns; one pair on their heads and another pair projecting from the abdomen; Adult: Has two white ring spots on the front wing and seven on the back wing of the top side. On the underside, there are three spots on the front wing and six on the back wing, all ringed with violet and yellow circles.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Satyridae',
          classification: '',
          treatment: '',
          sci_name: 'Melanitis leda ismene Cramer',
          eng_name: 'Green Horned Caterpillar (larva), Common Evening Brown (adult)',
          name: 'Greenhorned Caterpillar adult',
          image: '/img/pests/GreenhornedCaterpillaradult.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: '',
          description: 'Egg: Laid in small clusters openly on the leaf blades. Each egg is spherical and shiny; Larva: Has two pairs of white or black horns; one pair on their heads and another pair projecting from the abdomen; Adult: Has two white ring spots on the front wing and seven on the back wing of the top side. On the underside, there are three spots on the front wing and six on the back wing, all ringed with violet and yellow circles.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Satyridae',
          classification: '',
          treatment: '',
          sci_name: 'Melanitis leda ismene Cramer',
          eng_name: 'Green Horned Caterpillar (larva), Common Evening Brown (adult)',
          name: 'Greenhorned Caterpillar larva',
          image: '/img/pests/GreenhornedCaterpillarlarva.jpg'
       },
        
        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: 'Pagkaputol ng mga dahon ng pakanang dahilig na parang ginupit ng gunting. Pagkakaroon ng mga binilot na dahon na nagsisilbing proteksyon ng uod. Ang dahon ay nagmumukhang manipis na papel at hindi pantay-pantay na pagkaputol ng dahon. Sa ibang kaso, nagiging bansot ang mga dahon dahil mas gusto ng caseworn umatake sa murang yugto ng pagtubo ng palay.',
          fil_part_destroyed: 'Dahon, mga batang seedlings',
          fil_stage_threatening: 'Larva',
          fil_symptoms: 'Pagkakaroon ng mga nakasabit na binilot na parte ng dahon. Ang dulong parte ng dahon ay mistulang manipis na papel at mayroon hindi pantay-pantay na pagkasira ng mga dahon.',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: 'Kultural na pamamaraan: Mag-Crop Rotation. Linisin palagi ang palayan at bunutin ang mga damo. Para mabawasan ang mga larvae, igahin ang tubig ng hindi bababa sa tatlong araw. Tamang paggamit ng fertilizer, paglilipat-tanim ng mga matandang punla sa mas malawak na lugar.; Natural na pamamaraan: Ang mga itlog ng case worm ay pinaparasito ng Trichogramma (minutum Ashmead) at ang larvae naman ay kinakain ng (tabanid fly (Tabanus sp.?) at braconid wasp (Dacnusa sp.) samantalang ang hydrophilids, dystiscids at Cybister tripunctatus orientalis ay nagsisilbing predator ng caseworm. Ang mga itlog naman na nakadikit sa dahon ay kayang tanggalin ng mga kuhol (Pila sp. and Radix sp.). Kinakain din ng ilang mga gagamba ang caseworm.; Kemikal na pamamaraan: Foliar spray ng insecticides gaya ng carbamate, hindi lalagpas ng 7 araw pagka-transplant.',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Ladder-like appearance on the surface of leaves, leaf cases floating on water, leaves cut at right angles (like being cut with a pair of scissors), leaves with papery upper epidermis (whitish appearance).',
          description: 'Eggs: Pale, yellowish green, circular, somewhat flattened with a smooth surface, laid on the under surfaces of leaves drooping into the water; Larva: Young larva is pale cream, about 1.2 mm long and 0.2 mm across the head, and the head is light yellow. Full grown larva is about 14 mm long and 1.6 mm in diameter, and pale green with a semitransparent skin and light brown prothoracic shield and head; Pupa: 5.5 mm long and 1.5 mm wide, and is cream colored when freshly formed but turns silvery white toward moth emergence; Adult: 6mm long with a wing span of 15mm, white wings are marked with a few light brown to black specks and two or three submarginal fulvous bands.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Pyralidae',
          classification: '',
          treatment: 'Use of correct fertilizer application, plant early and use wider spacing (30 × 20 mm), drain the field, transplant older seedlings (sparse planting can also reduce the damage), grow a ratoon, encourage biological control agents (snails, hydrophilid and dytiscid water beetles, spiders, dragonflies, and birds), use foliar treatments of carbamate insecticides.',
          sci_name: 'Nymphula depunctalis (Guenée)',
          eng_name: 'Rice Caseworm',
          name: 'Rice Caseworm adult',
          image: '/img/pests/RiceCasewormadult.jpg'
       },
        
        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: 'Adult, larva',
          symptoms: '',
          description: 'Eggs: Yellow and develop purple to violet markings as they mature, laid in small clusters on leaf blades; Larva: Moves like inchworms, arching their backs as they go; Adult: Yellow orange with two diagonal, dark red bands on each front wing.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Noctuidae',
          classification: '',
          treatment: '',
          sci_name: 'Naranga aenescens (Moore)',
          eng_name: 'Green Semilooper',
          name: 'Rice Green Semilooper adult',
          image: '/img/pests/RiceGreenSemilooperadult.jpg'
       },

        {
          type: 'Pest',
          stage_threatening: 'Adult, larva',
          symptoms: '',
          description: 'Eggs: Yellow and develop purple to violet markings as they mature, laid in small clusters on leaf blades; Larva: Moves like inchworms, arching their backs as they go; Adult: Yellow orange with two diagonal, dark red bands on each front wing.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Noctuidae',
          classification: '',
          treatment: '',
          sci_name: 'Naranga aenescens (Moore)',
          fil_name: '',
          eng_name: 'Green Semilooper',
          name: 'Rice Green Semilooper larva',
          image: '/img/pests/RiceGreenSemilooperlarva.jpg'
       },
        
        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect:'Nakarolyo ang dahon. Pagkasira ng dahon at pag-iiba ng kulay nito. Mukhang nasunog at mahina ang dahon.',
          fil_part_destroyed:'Dahon',
          fil_stage_threatening: 'Larva',
          fil_symptoms:'May mga nakarolyo o nakatuping dahon. Ang paligid at dulo ng apektadong dahon ay natutuyo. Mukhang nasunog at mahina ang palay.',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment:'Kultural na pamamaraan: Gumamit ng barayti na maresistensya sa leaf folder. Bunutin ang mga damo dahil nagsisilbi itong alternatibong tirahan ng leaf folder. Pagtataas ng lebel ng tubig sa palayan pagkatapos umani upang hindi na makapangitlog ang mga leaf folder. Huwag masyadong masinsin ang mga pagtatanim. Mag-crop rotation.; Natural na pamamaraan: Ang leaf folder ay maraming mga natural na kalaban, kasama na rito ang parasitoids, predators at pathogens. Sa Pilipinas, ang Anaxipha longipennis at Metioche vittaticollis ay uri ng kagaykay ay kinakain ang mga itlog at uod ng leaffolder. Ang iba pang kalaban ng leaf folder ay plant (Cyrtorhinus lividipennis), pagong-pagungan (Micraspis crocea at Harmonia octomaculata). Ang pumapatay naman sa malaking leaf folder ay mga gagamba tulad ng Argiope catenulata. (CABI, 2005)',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: 'Adult, larva',
          symptoms: 'The first sign of leaffolder infestation is the presence of moths in the field. Longitudinal and transparent whitish streaks on damaged leaves, tubular folded leaves, and leaf tips sometimes fastened to the basal part of leaf are caused by larvae feeding. Severely damaged plants appear burned with many folded leaves. Under heavy attack, a field will appear gray white from a distance.',
          description: 'Eggs: Translucent, yellowish white, oval, 0.90 mm long and 0.39 mm wide, and almost flat with a slightly convex surface; Larva: Young larvae are translucent but turn yellowish green as they mature, head capsules and thoraxes are brown, have one pair of dark spots on the abdomen near the head; Pupa: Light brown, but turns reddish brown toward moth emergence; Adult: 10-12mm long and has wing span of 13-15mm; light brown with shiny, brownish yellow wings adorned with dark, broad margins, and two to three dark vertical stripes; appears triangular when at rest.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Pyralidae',
          classification: '',
          treatment: 'Careful use of nitrogenous fertilizer in split applications is recommended. Removal of grassy weeds from rice fields and surrounding borders prevents the buildup of rice leaffolders on alternate hosts. However, chemical control is the only practical method to control increasing leaffolder infestation during crop growth. Numerous insecticides that have been identified for control are most effective as foliar sprays. But foliar sprays have to be repeated because they are often washed off by frequent rains. Granular insecticides broadcast into water are ineffective. Since leaffolders can attack the crop during any growth stage, fields should be monitored weekly.',
          sci_name: 'Cnaphalocrocis medinalis (Guenée)',
          eng_name: 'Rice Leaffolder',
          name: 'Rice Leaffolder adult',
          image: '/img/pests/RiceLeaffolderadult.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect:'Nakarolyo ang dahon. Pagkasira ng dahon at pag-iiba ng kulay nito. Mukhang nasunog at mahina ang dahon.',
          fil_part_destroyed:'Dahon',
          fil_stage_threatening: 'Larva',
          fil_symptoms:'May mga nakarolyo o nakatuping dahon. Ang paligid at dulo ng apektadong dahon ay natutuyo. Mukhang nasunog at mahina ang palay.',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment:'Kultural na pamamaraan: Gumamit ng barayti na maresistensya sa leaf folder. Bunutin ang mga damo dahil nagsisilbi itong alternatibong tirahan ng leaf folder. Pagtataas ng lebel ng tubig sa palayan pagkatapos umani upang hindi na makapangitlog ang mga leaf folder. Huwag masyadong masinsin ang mga pagtatanim. Mag-crop rotation.; Natural na pamamaraan: Ang leaf folder ay maraming mga natural na kalaban, kasama na rito ang parasitoids, predators at pathogens. Sa Pilipinas, ang Anaxipha longipennis at Metioche vittaticollis ay uri ng kagaykay ay kinakain ang mga itlog at uod ng leaffolder. Ang iba pang kalaban ng leaf folder ay plant (Cyrtorhinus lividipennis), pagong-pagungan (Micraspis crocea at Harmonia octomaculata). Ang pumapatay naman sa malaking leaf folder ay mga gagamba tulad ng Argiope catenulata. (CABI, 2005)',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: 'Adult, larva',
          symptoms: 'The first sign of leaffolder infestation is the presence of moths in the field. Longitudinal and transparent whitish streaks on damaged leaves, tubular folded leaves, and leaf tips sometimes fastened to the basal part of leaf are caused by larvae feeding. Severely damaged plants appear burned with many folded leaves. Under heavy attack, a field will appear gray white from a distance.',
          description: 'Eggs: Translucent, yellowish white, oval, 0.90 mm long and 0.39 mm wide, and almost flat with a slightly convex surface; Larva: Young larvae are translucent but turn yellowish green as they mature, head capsules and thoraxes are brown, have one pair of dark spots on the abdomen near the head; Pupa: Light brown, but turns reddish brown toward moth emergence; Adult: 10-12mm long and has wing span of 13-15mm; light brown with shiny, brownish yellow wings adorned with dark, broad margins, and two to three dark vertical stripes; appears triangular when at rest.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Pyralidae',
          classification: '',
          treatment: 'Careful use of nitrogenous fertilizer in split applications is recommended. Removal of grassy weeds from rice fields and surrounding borders prevents the buildup of rice leaffolders on alternate hosts. However, chemical control is the only practical method to control increasing leaffolder infestation during crop growth. Numerous insecticides that have been identified for control are most effective as foliar sprays. But foliar sprays have to be repeated because they are often washed off by frequent rains. Granular insecticides broadcast into water are ineffective. Since leaffolders can attack the crop during any growth stage, fields should be monitored weekly.',
          sci_name: 'Cnaphalocrocis medinalis (Guenée)',
          eng_name: 'Rice Leaffolder',
          name: 'Rice Leaffolder larva',
          image: '/img/pests/RiceLeaffolderlarva.jpg'
       },
        
        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: 'Adult, larva',
          symptoms: '',
          description: 'Eggs: Pearl-like, laid singly on leaf blades; Larva: Heads are flat and slanted backward, have reddish vertical bands at each side of the head; Adult: White spots on brown wings, adults rest with their wings upright.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Hesperiidae',
          classification: '',
          treatment: '',
          sci_name: 'Pelopidas mathias (Fabricius)',
          fil_name: '',
          eng_name: 'Rice Skipper, Small Branded Swift, Black Branded Swift, Lesser Millet Skipper',
          name: 'Rice Skipper adult',
          image: '/img/pests/RiceSkipperadult.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: 'Adult, larva',
          symptoms: '',
          description: 'Eggs: Pearl-like, laid singly on leaf blades; Larva: Heads are flat and slanted backward, have reddish vertical bands at each side of the head; Adult: White spots on brown wings, adults rest with their wings upright.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Hesperiidae',
          classification: '',
          treatment: '',
          sci_name: 'Pelopidas mathias (Fabricius)',
          fil_name: '',
          eng_name: 'Rice Skipper, Small Branded Swift, Black Branded Swift, Lesser Millet Skipper',
          name: 'Rice Skipper larva',
          image: '/img/pests/RiceSkipperlarva.jpg'
       },
        
        {
          type: 'Pest',
          fil_stage_plant_affected:'Aksip',
          fil_effect:'Sa vegetative stage, nagdudulot ng dead tillers or deadhearts ang stem borer. Pagkakaroon ng uban sa reproductive stage. Pagkakaroon ng butas sa mga suwi at puno. Namamatay ang puno ng palay kung saan ang pinaka-ubod nito ay natutuyo. Kapansin-pansin din na ito ay madaling bunutin.',
          fil_part_destroyed:'katawan, suwi at uhay',
          fil_stage_threatening:'Larva',
          fil_symptoms:'Mayroong mga dead tillers o deadhearts sa vegetative stage. Madali itong bunutin. Pagkakaroon ng uban.',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment:'Kultural na pamamaraan: Gumamit ng variety na mas mabilis ang paglaki at hindi masyadong tumataas. Sabay-sabay na pagtatanim ng mga karatig na palayan. Gumamit ng barayti na maresistensya sa stem borer. Kung nagkaroon ng paglaganap ng stem borer sa palayan, tubigan pagka-ani upang matanggal ang mga itlog. Para mawala ang mga stem borer sa ibabang bahagi ng pananim, anihin ang palay sa hanggang sa ibabang bahagi.; Natural na pamamaraan: Kinakain ng mga Trichogramma, Telenomus, and Tetratichus (wasps) ang mga itlog ng stemborer. Kinakain rin ng kagaykay (kuliglig) (Metioche vittaticollis and Anaxipha longipennis) grasshopper (Conocephalus longipennis), mirid (Cytorhinus lividipennis) ang mga malalaking stem borer.',
          fil_name: 'Aksip',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: 'Adult, larva',
          symptoms: 'Larvae within the stems, signs of a stem being cut by larval feeding, insect excrements in stem, external discoloration and exit holes on the leaf sheath and stem, deadhearts (damage to the tiller before flowering), whiteheads (dry panicles the appear whitish); Egg masses are a sign that plant damage will occur; Large numbers of adult stem borer moths around lights indicate that large numbers of eggs will be laid that evening. ',
          description: 'Eggs: Laid near the tip of the leaf blade. Egg masses are disc-shaped and are covered by a light brown mat of hair from the females’ abdomen; Larva: Unmarked and range from light yellow to white; Adult: Bright white with no markings and has a distinctive tuft of long hairs on the thorax. Both sexes have similar coloration, but the male is smaller. Nocturnal, positively phototropic, and strong fliers.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Pyralidae',
          classification: '',
          treatment: 'Clipping the seedlings before transplanting greatly reduces the carryover of eggs from the seedbed to the transplanted fields. However, stem borers are difficult to control with insecticides. After hatching, the larvae are exposed only for a few hours before they penetrate a tiller or enter the plant. Successful control involves repeated foliar applications with spray volumes more than 400 liters/ha.',
          sci_name: 'Scirpophaga innotata (Walker)',
          eng_name: 'White Stemborer',
          name: 'White Stemborer',
          image: '/img/pests/WhiteStemborer.jpg'
       },
        
        {
          type: 'Pest',
          fil_stage_plant_affected:'Aksip',
          fil_effect:'Sa vegetative stage, nagdudulot ng dead tillers or deadhearts ang stem borer. Pagkakaroon ng uban sa reproductive stage. Pagkakaroon ng butas sa mga suwi at puno. Namamatay ang puno ng palay kung saan ang pinaka-ubod nito ay natutuyo. Kapansin-pansin din na ito ay madaling bunutin.',
          fil_part_destroyed:'katawan, suwi at uhay',
          fil_stage_threatening:'Larva',
          fil_symptoms:'Mayroong mga dead tillers o deadhearts sa vegetative stage. Madali itong bunutin. Pagkakaroon ng uban.',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment:'Kultural na pamamaraan: Gumamit ng variety na mas mabilis ang paglaki at hindi masyadong tumataas. Sabay-sabay na pagtatanim ng mga karatig na palayan. Gumamit ng barayti na maresistensya sa stem borer. Kung nagkaroon ng paglaganap ng stem borer sa palayan, tubigan pagka-ani upang matanggal ang mga itlog. Para mawala ang mga stem borer sa ibabang bahagi ng pananim, anihin ang palay sa hanggang sa ibabang bahagi.; Natural na pamamaraan: Kinakain ng mga Trichogramma, Telenomus, and Tetratichus (wasps) ang mga itlog ng stemborer. Kinakain rin ng kagaykay (kuliglig) (Metioche vittaticollis and Anaxipha longipennis) grasshopper (Conocephalus longipennis), mirid (Cytorhinus lividipennis) ang mga malalaking stem borer.',
          fil_name: 'Aksip',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: 'Adult, larva',
          symptoms: 'Larvae within the stems, signs of a stem being cut by larval feeding, insect excrements in stem, external discoloration and exit holes on the leaf sheath and stem, deadhearts (damage to the tiller before flowering), whiteheads (dry panicles the appear whitish); Egg masses are a sign that plant damage will occur; Large numbers of adult stem borer moths around lights indicate that large numbers of eggs will be laid that evening. ',
          description: 'Eggs: Laid near the tip of the leaf blade. Egg masses are disc-shaped and are covered by a light brown mat of hair from the females’ abdomen; Larva: Unmarked and range from light yellow to white; Adult: Female is pale yellow or light brown front wings, each with a characteristic single, black spot; male is smaller, gray or light brown, has two rows of small spots at the tip of each front wing. Nocturnal, positively phototropic, and strong fliers.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Pyralidae',
          classification: '',
          treatment: 'Clipping the seedlings before transplanting greatly reduces the carryover of eggs from the seedbed to the transplanted fields. However, stem borers are difficult to control with insecticides. After hatching, the larvae are exposed only for a few hours before they penetrate a tiller or enter the plant. Successful control involves repeated foliar applications with spray volumes more than 400 liters/ha.',
          sci_name: 'Scirpophaga incertulas (Walker)',
          eng_name: 'Yellow Stemborer',
          name: 'Yellow Stemborer adult',
          image: '/img/pests/YellowStemboreradult.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected:'Aksip',
          fil_effect:'Sa vegetative stage, nagdudulot ng dead tillers or deadhearts ang stem borer. Pagkakaroon ng uban sa reproductive stage. Pagkakaroon ng butas sa mga suwi at puno. Namamatay ang puno ng palay kung saan ang pinaka-ubod nito ay natutuyo. Kapansin-pansin din na ito ay madaling bunutin.',
          fil_part_destroyed:'katawan, suwi at uhay',
          fil_stage_threatening:'Larva',
          fil_symptoms:'Mayroong mga dead tillers o deadhearts sa vegetative stage. Madali itong bunutin. Pagkakaroon ng uban.',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment:'Kultural na pamamaraan: Gumamit ng variety na mas mabilis ang paglaki at hindi masyadong tumataas. Sabay-sabay na pagtatanim ng mga karatig na palayan. Gumamit ng barayti na maresistensya sa stem borer. Kung nagkaroon ng paglaganap ng stem borer sa palayan, tubigan pagka-ani upang matanggal ang mga itlog. Para mawala ang mga stem borer sa ibabang bahagi ng pananim, anihin ang palay sa hanggang sa ibabang bahagi.; Natural na pamamaraan: Kinakain ng mga Trichogramma, Telenomus, and Tetratichus (wasps) ang mga itlog ng stemborer. Kinakain rin ng kagaykay (kuliglig) (Metioche vittaticollis and Anaxipha longipennis) grasshopper (Conocephalus longipennis), mirid (Cytorhinus lividipennis) ang mga malalaking stem borer.',
          fil_name: 'Aksip',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: 'Adult, larva',
          symptoms: 'Larvae within the stems, signs of a stem being cut by larval feeding, insect excrements in stem, external discoloration and exit holes on the leaf sheath and stem, deadhearts (damage to the tiller before flowering), whiteheads (dry panicles the appear whitish); Egg masses are a sign that plant damage will occur; Large numbers of adult stem borer moths around lights indicate that large numbers of eggs will be laid that evening. ',
          description: 'Eggs: Laid near the tip of the leaf blade. Egg masses are disc-shaped and are covered by a light brown mat of hair from the females’ abdomen; Larva: Unmarked and range from light yellow to white; Adult: Female is pale yellow or light brown front wings, each with a characteristic single, black spot; male is smaller, gray or light brown, has two rows of small spots at the tip of each front wing. Nocturnal, positively phototropic, and strong fliers.',
          plant_affected: 'Rice',
          order: 'Lepidoptera: Pyralidae',
          classification: '',
          treatment: 'Clipping the seedlings before transplanting greatly reduces the carryover of eggs from the seedbed to the transplanted fields. However, stem borers are difficult to control with insecticides. After hatching, the larvae are exposed only for a few hours before they penetrate a tiller or enter the plant. Successful control involves repeated foliar applications with spray volumes more than 400 liters/ha.',
          sci_name: 'Scirpophaga incertulas (Walker)',
          eng_name: 'Yellow Stemborer',
          name: 'Yellow Stemborer larva',
          image: '/img/pests/YellowStemborerlarva.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: 'Adult, larva',
          symptoms: 'Presence of larvae on food plants, presence of pupae in cocoon attached to underside of leaves, and skeletonized leaves by larval feeding.',
          description: 'Egg: White to pale green and shiny, dome-shaped with 28-32 vertical ribs from the micropyle to the base; Larva: About 40 mm wingspan and 15-18 mm long, forewing gold to bronze in ground color and has two silver oval spots that are similar in size; Pupa About 20 mm long, pale green ventrally with a dark brown dorsal stripe, or body entirely brown; Adult: About 40 mm wingspan and 15-18 mm long; forewing gold to bronze in ground color and has two silver oval spots that are similar in size.',
          plant_affected: 'Corn',
          order: 'Lepidoptera: Noctuidae',
          classification: '',
          treatment: '',
          sci_name: 'Chrysodeixis chalcites Esper',
          eng_name: 'Corn Semilooper, Tomato Looper, Green Gardern Looper (larva); Golden Twin Spot (adult)',
          name: 'Corn Semilooper adult',
          image: '/img/pests/CornSemilooperadult.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: 'Adult, larva',
          symptoms: 'Presence of larvae on food plants, presence of pupae in cocoon attached to underside of leaves, and skeletonized leaves by larval feeding.',
          description: 'Egg: White to pale green and shiny, dome-shaped with 28-32 vertical ribs from the micropyle to the base; Larva: About 40 mm wingspan and 15-18 mm long, forewing gold to bronze in ground color and has two silver oval spots that are similar in size; Pupa About 20 mm long, pale green ventrally with a dark brown dorsal stripe, or body entirely brown; Adult: About 40 mm wingspan and 15-18 mm long; forewing gold to bronze in ground color and has two silver oval spots that are similar in size.',
          plant_affected: 'Corn',
          order: 'Lepidoptera: Noctuidae',
          classification: '',
          treatment: '',
          sci_name: 'Chrysodeixis chalcites Esper',
          eng_name: 'Corn Semilooper, Tomato Looper, Green Gardern Looper (larva); Golden Twin Spot (adult)',
          name: 'Corn Semilooper larva',
          image: '/img/pests/CornSemilooperlarva.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: 'Adult',
          symptoms: 'Feeding damage on leaves and in the whorl; boring in the stems, tassels, ears and midribs which can lead to lodging, breaking of tassels, and dropping of ears.',
          description: '',
          plant_affected: 'Corn',
          order: 'Lepidoptera: Crambidae',
          classification: '',
          treatment: '',
          sci_name: 'Ostrinia furnacalis Guenee',
          eng_name: 'Asian/Oriental Cornborer',
          name: 'Asian Cornborer adult',
          image: '/img/pests/AsianCornboreradult.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Eggs are laid on the silks, larvae invade the cobs and developing grain is consumed. Secondary bacterial infections are common.',
          description: 'Egg: pale green when first deposited, becoming yellowish and then gray with time; shape varies from slightly dome-shaped to a flattened sphere, and measures about 0.5-0.6 mm in diameter and 0.5 mm in height; Larva: Full-grown larvae are about 30-40 mm long; the head is brown and mottled; the prothoracic and supra-anal plates and legs are pale-brown, only claws and spiracles remaining black; the final body segment is elongated; Pupa: mahogany-brown in color, and measures 17 to 22 mm in length and 5.5 mm in width; Adult:  has wingspan of 32-45mm; forewings are usually yellowish brown in color, and often bear a small dark spot centrally; forewing also may bear a broad dark transverse band distally, but the margin of the wing is not darkened; hind wings are creamy white basally and blackish distally, and usually bear a small dark spot centrally.',
          plant_affected: 'Corn',
          order: 'Lepidoptera: Noctuidae',
          classification: '',
          treatment: '',
          sci_name: 'Helicoverpa armigera Hubner',
          eng_name: 'Corn Earworm, Cotton Bollwormm, Tobacco Budworm (larva); Scarce Bordered Straw (adult)',
          name: 'Corn Earworm adult',
          image: '/img/pests/CornEarwormadult.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Eggs are laid on the silks, larvae invade the cobs and developing grain is consumed. Secondary bacterial infections are common.',
          description: 'Egg: pale green when first deposited, becoming yellowish and then gray with time; shape varies from slightly dome-shaped to a flattened sphere, and measures about 0.5-0.6 mm in diameter and 0.5 mm in height; Larva: Full-grown larvae are about 30-40 mm long; the head is brown and mottled; the prothoracic and supra-anal plates and legs are pale-brown, only claws and spiracles remaining black; the final body segment is elongated; Pupa: mahogany-brown in color, and measures 17 to 22 mm in length and 5.5 mm in width; Adult:  has wingspan of 32-45mm; forewings are usually yellowish brown in color, and often bear a small dark spot centrally; forewing also may bear a broad dark transverse band distally, but the margin of the wing is not darkened; hind wings are creamy white basally and blackish distally, and usually bear a small dark spot centrally.',
          plant_affected: 'Corn',
          order: 'Lepidoptera: Noctuidae',
          classification: '',
          treatment: '',
          sci_name: 'Helicoverpa armigera Hubner',
          fil_name: '',
          eng_name: 'Corn Earworm, Cotton Bollwormm, Tobacco Budworm (larva); Scarce Bordered Straw (adult)',
          name: 'Corn Earworm larva',
          image: '/img/pests/CornEarwormlarva.jpg'
       },

        //FREI
        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Stunting, wilting on the plant and linear lesions on the leaves with wavy edges caused by Stewart\'s Wilt. ',
          description: 'Corn flea beetle is a very tiny (1.8 mm), black, shiny beetles with elongated hind legs, which are used for jumping when disturbed.',
          plant_affected: 'Corn',
          order: 'Coleoptera',
          classification: '',
          treatment: 'Cut off their food supply by delaying transplanting or planting by a couple weeks if possible. Corn flea beetle feeding may be reduced with the use of insecticidal seed treatments and foliar insecticides.',
          sci_name: 'Chaetocnema pulicaria',
          eng_name: 'Corn Flea Beetle, Clover Flea Beetle',
          name: 'Corn Flea Beetle',
          image: '/img/pests/CornFleaBeetle.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'The leaf of the plant becomes membranous and dry.',
          description: 'Small, metallic blue beetles with a series of black dots on the elytra. It measures 1/4th to 1/5th of an inch in length and 1/8th inch in width.',
          plant_affected: 'Rice',
          order: 'Coleoptera: Chrysomelidae: Hispinae',
          classification: '',
          treatment: 'Deep and thorough ploughing of the field and crop rotation will be a great help. It is also possible to pluck the infected leaves in minor infection and uproot the whole plant in case of major infection.',
          sci_name: 'Leptispa Pygmaea',
          eng_name: 'Rice Blue Beetle',
          name: 'Leptispa',
          image: '/img/pests/Leptispa.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'There will be increased moisture levels and heating on the surface due to the weevil\'s respiration. Seeds with round holes are formed by exiting adults.',
          description: 'A small weevil that is usually 1/10 inch (2 to 3 mm) in size and stout in appearance. It is reddish-brown to black in color with four light yellow or reddish spots on the corners of the elytra. The snout is long (1 mm), almost 1/3 of the total length.',
          plant_affected: 'Rice',
          order: 'Coleoptera : Curculionidae',
          classification: '',
          treatment: 'Control of these insects by seed treatments is reliant on either the adults, in the case of cypermethrin, or larvae, when triflumuron is used, feeding on the treated grain and hence the insecticide. When feeding on treated grain, insecticide is ingested and the insect is killed.',
          sci_name: 'Sitophilus Oryzae',
          eng_name: 'Rice Weevil',
          name: 'Rice Weevil',
          image: '/img/pests/RiceWeevil.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Scraping of the upper surface of the leaf blade leaving only the lower epidermis as white streaks parallel to the midrib. Tunneling of larvae through leaf tissue causes irregular translucent white patches that are parallel to the leaf veins.',
          description: 'It is a small bluish-black beetle fringed with numerous short spines over the body.',
          plant_affected: 'Rice',
          order: 'Coleoptera: Chrysomeloidea: Chrysomelidae',
          classification: '',
          treatment: 'A cultural control method that is recommended for the rice hispa is to avoid over fertilizing the field. Close plant spacing results in greater leaf densities that can tolerate higher hispa numbers. To prevent egg laying of the pests, the shoot tips can be cut. Clipping and burying shoots in the mud can reduce grub populations by 75−92%.',
          sci_name: 'Dicladispa Armigera',
          eng_name: 'Rice Hispa, Spiny Beetle',
          name: 'Rice Hispa',
          image: '/img/pests/RiceHispa.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Because white grubs feed on roots, damage is usually first noticed during dry periods when injured plants cannot get the water they need. Turf often dies in large, irregular-shaped patches.',
          description: 'White grubs are the larval stage of certain beetles, called scarabs. They are fairly large, creme-colored larvae with 3 distinct pairs of legs and an amber-colored head.',
          plant_affected: 'Rice, Corn',
          order: 'Coleoptera: Scarabaeidae',
          classification: '',
          treatment: 'There are a number of natural enemies including predators such as wasps, beetles and ants that control white grubs. Two biological control products that are presently available to the consumer are milky spore disease and parasitic nematodes.',
          sci_name: 'Phyllophaga',
          eng_name: 'White Grub, Scarab Larvae',
          name: 'White Grub Larva',
          image: '/img/pests/WhiteGrubLarva.jpg'
       },

        //JASON
        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Irregular to longitudinal exit holes on leaves. Damage on stems, seeds, roots, and on young panicles of the rice plant. Dreadheart.',
          description: 'Can grow up to an inch long, and are black and brown. They have large hind legs and two cerci (spiky things coming out of the back of their abdomens).',
          plant_affected: 'Rice',
          order: 'Orthoptera',
          classification: '',
          treatment: 'There are no known control practices for this insect.',
          sci_name: 'Euscyrtus Concinnus',
          eng_name: 'Cricket, Gryllids',
          name: 'Field Cricket',
          image: '/img/pests/FieldCricket.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Chewed edges of leaves, flowers or buds, holes in leaves, flowers or buds, gray scar tissue on fruit.',
          description: 'They range in size from as small as 5mm to as large as 130mm. They are usually green, sometimes with brown markings. They have a thick body, usually taller than it is wide, and long thing legs. The hind legs are longer than the front or middle legs, and are often used for jumping. On the head they have chewing mouthparts and long thin antennae that reach back at least to the abdomen of the insect.',
          plant_affected: 'Rice, Corn',
          order: 'Orthoptera',
          classification: '',
          treatment: 'Remove long grass around affected plants to eliminate hiding places. Encourage biological control by attracting their predators to the garden – bats, birds and snakes.',
          sci_name: 'Tettigoniidae sp.',
          eng_name: 'Katydid, Bush Cricket, Long-horned Grasshopper',
          name: 'Katydid',
          image: '/img/pests/Katydid.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Both young and adult stages feed upon the leaves and shoots of paddy. They also cut off the ear heads.',
          description: 'The adults are medium sized insects, uniformly greenish and practically without any spot. They measures about 5 cms in length.',
          plant_affected: 'Rice',
          order: 'Orthoptera',
          classification: '',
          treatment: 'Dusting the crop with to 10% BHC or 5% Aldrin is very much effective. Poison baiting is useful both against nymphs and adults. The egg masses are destroyed by ploughing the field and exposing them to birds.',
          sci_name: 'Oxya hyla intricata ',
          eng_name: 'Rice Grasshopper, Short-horned Grasshopper',
          name: 'Short-horned Grasshopper',
          image: '/img/pests/Short-hornedGrasshopper.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Cut out areas on leaves and cut-off panicles. Presence of yellow and brown nymphs and adults feeding on rice foliage.',
          description: 'Large size and absence of prosternal tubercule. Other distinctive characteristics concern the wings: smoky at the apex (radial sector) and black veins in the anal sector.',
          plant_affected: 'Rice',
          order: 'Orthoptera: AcrididaeLarge',
          classification: '',
          treatment: 'Flood the stubbles, shave bunds, sweep along the bunds and pick adults directly from the foliage at night when they are sluggish. Use poison baits from salt water and rice bran. Use foliar sprays to control grashoppers in rice fields. Granules are not effective.',
          sci_name: 'Locusta migratoria manilensis',
          eng_name: 'Oriental Migratory Locust, Asiatic Migratory Locust',
          name: 'Oriental Migratory Locust',
          image: '/img/pests/OrientalMigratoryLocust.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'The crickets usually damage seedlings, feeding aboveground on foliage or stem tissue, and belowground on roots and tubers. Girdling of the stems of seedling plants at the soil surface is a common form of injury, though young plants are sometimes severed and pulled belowground to be consumed. Additional injury to small plants is caused by soil surface tunneling, which may dislodge seedlings or cause them to desiccate.',
          description: 'Mole crickets are cylindrical-bodied insects about 3–5 centimetres (1.2–2.0 in) long, with small eyes and shovel-like forelimbs highly developed for burrowing.',
          plant_affected: 'Rice',
          order: 'Orthoptera',
          classification: '',
          treatment: 'Maintain standing water. Encourage biological control agents: sphecid wasp, carabid beetle, nematodes, and fungus; mole crickets eat each other when they are together because of their cannibalistic behavior.',
          sci_name: 'Gryllotalpa orientalis',
          eng_name: 'Short-winged Mole Cricket, Southern Mole Cricket, Tawny Mole Cricket',
          name: 'Mole Cricket',
          image: '/img/pests/MoleCricket.jpg'
       },

        //JV
        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect:'Sinisipsip ng plant hopper ang katas ng palay kaya nagiging chlorotic (maputla o naninilaw) ang mga dahon nito. Nagsisimula ito sa tip ng dahon patungo sa gitnang bahagi ng dahon hanggang sa tuluyan itong mamatay, ang kondisyong ito ang tinatawag na hopperburn. Sa umpisa, mukha lang may patse-patse sa palayan, ngunit mabilis itong dumami sa pamamagitan ng paglipat-lipat nito mula sa isang palay patungo sa kabila. Ang brown plant hopper ay maaaring mayroon dalang rice ragged stunt at grassy stunt virus.',
          fil_part_destroyed:'Katawan',
          fil_stage_threatening:'Nimpa hanggang magulang na insekto',
          fil_symptoms:'May hopperburn ang palayan. Tingnan kung may sintomas ng rice ragged stunt at grassy stunt virus.',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment:'Kultural na pamamaraan: Mag-crop rotation. Gumamit ng ng mga legumes bilang pamalit sa palay. Split application ng Nitrogen fertilizer at pagtanggal ng tubig sa palayan sa loob ng 3-4 na araw upang mabasawasan ang dami ng plant hopper.; Natural na pamamaraan: Kumakain ng itlog the brown leafhopper ang mga parasitoids gaya ng eulophid wasps (Tetrastichus formosus Timberlake), mymarid (Anagru soptabilis Perkins), trichogrammatid (Paracentrobia andoi Ishii). Kumakain naman ng plant hopper ang dryinid wasp (Echthrodelphax bicolor), Elenchus yasumatsui, beetle (Ophioneaiskii Habu); fungal pathogens gaya ng Hirsutella citriformis at Beauveria bassiana; nematode parasite Hexamermis sp.',
          fil_name: 'Kayumangging hanip, Kayumangging ngusong kabayo',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Hopperburn or yellowing, browning and drying of plant, ovipositional marks exposing the plant to fungal and bacterial infections, presence of honeydew and sooty molds in the bases of areas infected, plants with ragged stunt or grassy stunt virus disease.',
          description: 'Adults occur in macropterous (long-winged) and brachypterous (short-winged) forms. The macropterous form is about 3.5 – 4.5 mm in length. The body is brown, and the wings are transparent, with very conspicuous veins. Young nymphs are white, but they gradually become darker in older instars.',
          plant_affected: 'Rice',
          order: 'Hemiptera',
          classification: '',
          treatment: ' Flood the seedbed, for a day, so that only the tips of seedlings are exposed will control BHP. Sweep small seedbeds with a net to remove some BPH (but not eggs), particularly from dry seed beds. At high BPH densities, sweeping will not remove sufficient numbers of BPH from the base of the plant.',
          sci_name: 'Nilaparvata lugens',
          eng_name: 'Brown Planthopper, Planthopper',
          name: 'Brown Planthopper',
          image: '/img/pests/BrownPlanthopper.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect:'Kapag hindi masyadong marami ang green leaf hopper sa inyong palayan, hindi masyado pansin ang epekto nito. Madaling lumawak ang epekto ng green leaf hopper dahil kaya nitong lumipat patungo sa iba pang palay. Pinapasok ng leaf hopper ang malakarayom na nguso nito sa leaf tissue, sa paraang ito maaring masalin ng leaf hopper ang virus na dala nito. Ang mga palayan na may green leaf hopper ay maaaring mayroon ding tungro o yellow-dwarf disease. Ito ay may kakaunting suwi at naninilaw hanggang sa matuyo ang apektadong palay (dahil sa tungro).',
          fil_part_destroyed:'Dahon',
          fil_stage_threatening:'Nimpa hanggang magulang na insekto',
          fil_symptoms:'Bansot at kakaunti ang suwi. Ang mga apektadongpalay ay naninilaw hanggang sa ito matuyo',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment:'Natural na pamamaraan: Ang mga itlog ng green leaf hopper ay kinakain ng mymarid wasps (Anagrus soptabilis Perkins and Gonatocerus sp.), trichogrammatid wasps (Paraentrobia andoi Ishii). Ang malalaki naming mga green leaf hopper ay kinakain ng dryinid wasp (Echthrodelphax fairchildii Perkins), strepsipteran (Halictophagus munroei Hirashima and Kifune), pipunculid flies (Pipunculus mutillatus Loew and Tomosvaryella oryzaetora Koizumi)',
          fil_name: 'Ngusong Kabayo',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Stunted plants and reduced vigor, reduced number of productive tillers, withering or complete plant drying.',
          description: 'The thickened part of the antennae is very short and ends with a bristle (arista). Two ocelli (simple eyes) are present on the top or front of the head. The tarsi are made of three segments. The femora are at front with, at most, weak spines. The hind tibiae have one or more distinct keels, with a row of movable spines on each, sometimes on enlarged bases.',
          plant_affected: 'Rice',
          order: 'Hemiptera',
          classification: '',
          treatment: 'Reduce the number of rice crops to two per year and synchronized crop establishment across farms reduces leafhoppers and other insect vectors. Transplant older seedlings (>3 weeks) to reduce viral disease susceptibility transmitted by leafhoppers. Plant early within a given planting period, particularly in the dry season to reduce the risk of insect-vector disease.',
          sci_name: 'Nephotettix malayanus, Nephotettix virescens, Nephotettix nigropictus Stal',
          eng_name: 'Green Leafhopper, Leafhopper, Hopper',
          name: 'Green Leafhopper',
          image: '/img/pests/GreenLeafhopper.jpg'
       }, 

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Drying of leaf tips, whole leaves become orange and leaf margins become orange and curl.',
          description: 'Zigzag Leafhopper are plant-sucking pest that are usually, brown to white. They are easily recognized by the striped markings on its wings.',
          plant_affected: 'Rice',
          order: 'Hemiptera',
          classification: '',
          treatment: 'There are parasites and predators that help regulate the population of this insect. Mymarid wasps and the mirid bugs prey on the eggs. Dryinid wasps and pipunculid flies parasitize both the adults and the nymphs and spiders eat the adults.',
          sci_name: 'Recilia dorsalis',
          eng_name: 'Zigzag Leafhopper',
          name: 'Zigzag Leafhopper',
          image: '/img/pests/ZigzagLeafhopper.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Heavy infestation causes stunted growth, formation of white heads, half-filled or empty grains, and browning of leaves or bug burn. ',
          description: 'It is white and tinged with green and pink and turns shiny brownish black to shiny black as it matures. It is 8-9 mm long. The nymphs are brown or yellow in color. Black spots are visible on their bodies. Different nymphal instars vary in sizes. Six nymphal instars are completed in 29-35 days.',
          plant_affected: 'Rice, Corn',
          order: 'Hemiptera',
          classification: '',
          treatment: 'Maintain a clean field by removing the weeds and drying the rice field during plowing. Plant rice varieties of the same maturity date to break the insect’s cycle. Use of mercury bulbs as light traps for egg-laying adults, light trapping of insects should start 5 days before and after the full moon.',
          sci_name: 'Scotinophara coarctata',
          eng_name: 'Black Bug, Common Black Bug',
          name: 'Black Bug',
          image: '/img/pests/BlackBug.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Formation of a hollow cavity or tubular gall at the base of the infested tiller. The gall formed is a silvery white hollow tube, 1 cm wide and 10−30 cm long, affected tiller inhibits growth of leaves and fails to produce panicles, deformed, wilted, and rolled leaf, elongation of leaf sheaths, also called onion leaf or silvershoot and plant stunting',
          description: 'Rice Gall Midge are very fragile small insects usually only 2–3 mm in length; many are less than 1 mm long. They are characterised by hairy wings, unusual in the order Diptera, and have long antennae.',
          plant_affected: 'Rice',
          order: 'Hemiptera',
          classification: '',
          treatment: 'Plow ratoon of the previous crop and remove all off-season plant hosts. Encourage biological control agents: platygasterid, eupelmid, and pteromalid wasps (parasitize the larvae), phytoseiid mites (feed on eggs), spiders (feed on adults).',
          sci_name: 'Orseolia oryzae',
          eng_name: 'Gall Midge, Rice Gall Midge, Asian Gall Midge',
          name: 'Rice Gall Midge',
          image: '/img/pests/RiceGallMidge.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Wilting, plant stunting, yellowish curled leaves and damaged spots or chakdhora or soorai disease.',
          description: 'Small sap-sucking insect that is observed most frequently for its ovoid, sluggish mature female, about 1 cm (0.4 inch) long.',
          plant_affected: 'Rice',
          order: 'Hemiptera',
          classification: '',
          treatment: 'Encourage biological control agents: small encyrtid wasps, spiders, chloropid fly, drosophilid, and lady beetles.',
          sci_name: 'Brevennia rehi',
          eng_name: 'Rice Mealy Bug, Mealy Bug',
          name: 'Rice Mealy Bug',
          image: '/img/pests/RiceMealyBug.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect:'Sa soft dough stage, sinisipsip ng rice bugs ang mga butil kaya ito nagkakaroon ng sira o kaya pagkawala ng laman ng mga butil',
          fil_part_destroyed: '',
          fil_stage_threatening:'Nimpa hanggang magulang na insekto',
          fil_symptoms:'Ang mga butil ay may paltak na itim, wala sa tamang hugis o kaya naman ay walang laman. May mabahong amoy na mapapansin sa palayan. Mapapansin ang maliliit nitong mga itlog na kulay kayumanggi na parang nahahanay sa dahon ng palay.',
          fil_description:'Payat na pahaba, kulay kayumanggi',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment:'Kultural na pamamaraan: Pagtatanim kasabay ang mga karatig na palayan. Bunutin ang mga damo dahil nagsisilbi itong alternatibong tirahan ng rice bug. Pantay na paglalagay ng pataba at tubig sa buong palayan upang sabay-sabay ang paglaki nito. Gumamit ng barayti na maresistensya sa Rice Bug (need help from expert). Upang masira ang life cycle ng Rice Bug magtanim ng palay na sabay-sabay ang paglaki.;Natural na pamamaraan: Iwasang patayin ang mga natural nitong kaaway tulad ng (need help from CPC group)',
          fil_name: 'Atangya',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'Small or shriveled grains, deformed or spotty grains, empty grains, erect panicles and foul odor',
          description: 'Leptocorisa acuta adults are long (14-17 mm) and slender (3-4 mm wide). They are a light yellow-green to yellow-brown color. The head is broad, often similar in length and width to the pronotum (upper surface of the first plate on the thorax) and the scutellum (triangular shaped plate on the thorax, posterior to the pronotum).',
          plant_affected: 'Rice',
          order: 'Hemiptera',
          classification: '',
          treatment: 'Capturing rice bugs, in the early morning or late afternoon, by net can be effective at low rice bug densities, though labor intensive. Encourage biological control agents: Some wasps, grasshoppers and spiders attack rice bugs or rice bug eggs. Indiscriminate insecticide use disrupts biological control, resulting in pest resurgence.',
          sci_name: 'Leptocorisa Varicornis, Leptocorisa oratorius Fab., Leptocorisa acuta Thunberg',
          eng_name: 'Rice Paddy Bug, Rice Bug, Paddy Bug',
          name: 'Rice Paddy Bug',
          image: '/img/pests/RicePaddyBug.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: '',
          fil_effect: '',
          fil_part_destroyed: '',
          fil_stage_threatening: '',
          fil_symptoms: '',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment: '',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: 'If root aphid infestation is very severe, stunting and leaf yellowing may occur. The stunting can be compared with the damage caused by root grubs.',
          description: 'Fully grown aphids are 1.2 - 2.2 mm long and dark green to grey-brown in colour. Nymphs are lighter in colour with a reddish area at the tip of the abdomen.',
          plant_affected: 'Rice',
          order: 'Hemiptera',
          classification: '',
          treatment: 'Encourage biological control agents or natural enemies that can manage the population of rice root aphids. Both the nymphs and adults are parasitized by a small braconid wasp and a mermithid nematode and are preyed upon by lady beetles.',
          sci_name: 'Tetraneura nigriabdominalis',
          eng_name: 'Rice Root Aphid, Aphid',
          name: 'Rice Root Aphid',
          image: '/img/pests/RiceRootAphid.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected: 'Mula transplanting hanggang sa vegetative na stage.',
          fil_effect:'Kinakain ng rice whorl maggot ang mga umuusbong pa lang na mga dahon. Ito ang nagiging dahilan ng pagkakaroon ng mga sugat sa mga dahon. Nababansot at naninilaw ang mga dahon at nagkakaroon ng mga butas-butas. Madaling nasisira ang mga dahon sa hampas ng hangin.',
          fil_part_destroyed: 'Dahon',
          fil_stage_threatening: 'Larva/Maggot',
          fil_symptoms: 'Pagkakaroon ng pa-isa-isang pahaba na maputing itlog na nakadikit sa palay. Pagkakaroon ng kulay malagatas (cream) na uod na nagiging madilaw kapag lumaki. Kinakain nito ang pausbong pa lamang na dahon. Pagkakaroon ng manipis at mala-papel na patse sa dahon. Ang mga batang dahon ay bansot at naninilaw. Madaling nasisira ang mga dahon sa hampas ng hangin.',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment:'Kultural na pamamaraan: Gumamit ng barayti na may resistensya sa Rice Whorl Maggot. Plant spacing.; Natural na pamamaraan: Iwasang patayin ang mga natural nitong kaaway gaya ng __________ (need help from CPC); Kemikal na pamamaraan: Hindi nirerekomenda ang paggamit ng kemikal sa Rice Whorl Maggot dahil ang pinsala nito ay hanggang early tillering stage lamang.',
          fil_name: '',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: '',
          symptoms: '',
          description: '',
          plant_affected: 'Rice',
          order: '',
          classification: '',
          treatment: '',
          sci_name: 'Hydrellia philippina (Ferino)',
          eng_name: '',
          name: 'Rice Whorl Maggot',
          image: '/img/pests/RiceWhorlMaggot.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected:'Aksip',
          fil_effect:'Sa vegetative stage, nagdudulot ng dead tillers or deadhearts ang stem borer. Pagkakaroon ng uban sa reproductive stage. Pagkakaroon ng butas sa mga suwi at puno. Namamatay ang puno ng palay kung saan ang pinaka-ubod nito ay natutuyo. Kapansin-pansin din na ito ay madaling bunutin.',
          fil_part_destroyed:'katawan, suwi at uhay',
          fil_stage_threatening:'Larva',
          fil_symptoms:'Mayroong mga dead tillers o deadhearts sa vegetative stage. Madali itong bunutin. Pagkakaroon ng uban.',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment:'Kultural na pamamaraan: Gumamit ng variety na mas mabilis ang paglaki at hindi masyadong tumataas. Sabay-sabay na pagtatanim ng mga karatig na palayan. Gumamit ng barayti na maresistensya sa stem borer. Kung nagkaroon ng paglaganap ng stem borer sa palayan, tubigan pagka-ani upang matanggal ang mga itlog. Para mawala ang mga stem borer sa ibabang bahagi ng pananim, anihin ang palay sa hanggang sa ibabang bahagi.; Natural na pamamaraan: Kinakain ng mga Trichogramma, Telenomus, and Tetratichus (wasps) ang mga itlog ng stemborer. Kinakain rin ng kagaykay (kuliglig) (Metioche vittaticollis and Anaxipha longipennis) grasshopper (Conocephalus longipennis), mirid (Cytorhinus lividipennis) ang mga malalaking stem borer.',
          fil_name: 'Aksip',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: 'Adult, larva',
          symptoms: '',
          description: '',
          plant_affected: 'Rice',
          order: '',
          classification: '',
          treatment: '',
          sci_name: 'Chilo suppressalis Walker',
          eng_name: '',
          name:'Striped Stemborer',
          image: '/img/pests/StripedStemborer.jpg'
       },

        {
          type: 'Pest',
          fil_stage_plant_affected:'Aksip',
          fil_effect:'Sa vegetative stage, nagdudulot ng dead tillers or deadhearts ang stem borer. Pagkakaroon ng uban sa reproductive stage. Pagkakaroon ng butas sa mga suwi at puno. Namamatay ang puno ng palay kung saan ang pinaka-ubod nito ay natutuyo. Kapansin-pansin din na ito ay madaling bunutin.',
          fil_part_destroyed:'katawan, suwi at uhay',
          fil_stage_threatening:'Larva',
          fil_symptoms:'Mayroong mga dead tillers o deadhearts sa vegetative stage. Madali itong bunutin. Pagkakaroon ng uban.',
          fil_description: '',
          fil_plant_affected: '',
          fil_classification: '',
          fil_treatment:'Kultural na pamamaraan: Gumamit ng variety na mas mabilis ang paglaki at hindi masyadong tumataas. Sabay-sabay na pagtatanim ng mga karatig na palayan. Gumamit ng barayti na maresistensya sa stem borer. Kung nagkaroon ng paglaganap ng stem borer sa palayan, tubigan pagka-ani upang matanggal ang mga itlog. Para mawala ang mga stem borer sa ibabang bahagi ng pananim, anihin ang palay sa hanggang sa ibabang bahagi.; Natural na pamamaraan: Kinakain ng mga Trichogramma, Telenomus, and Tetratichus (wasps) ang mga itlog ng stemborer. Kinakain rin ng kagaykay (kuliglig) (Metioche vittaticollis and Anaxipha longipennis) grasshopper (Conocephalus longipennis), mirid (Cytorhinus lividipennis) ang mga malalaking stem borer.',
          fil_name: 'Aksip',
          stage_plant_affected: '',
          effect: '',
          part_destroyed: '',
          stage_threatening: 'Adult, larva',
          symptoms: '',
          description: '',
          plant_affected: 'Rice',
          order: '',
          classification: '',
          treatment: '',
          sci_name: 'Sesamia inferens Walker',
          eng_name: '',
          name:'Pink Stemborer',
          image: '/img/pests/PinkStemborer.jpg'
       }
    ];

    data.forEach(pests => Pests.insert(pests));
  }
});
